name: CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run prettier

      - name: Test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with: 
          annotations: none

      - name: Build  
        run: npm run build

